[9.0][MIG] geoengine partner
OCA/geospatial pull request #128
Opened 2017-02-17 14:57 UTC by yvaucher

2017-02-19 05:24 UTC, elicoidal requested changes
some details, no tests

2017-02-19 05:24 UTC, elicoidal commented on geoengine_partner/README.rst
> +Open a partner form and go in `Geoengine Map` tab.
Can you use enumerated list? It is easier to follow for SOP

2017-02-19 05:24 UTC, elicoidal commented on geoengine_partner/__openerp__.py
> + 'version': '9.0.0.1.0',
9.0.1.0.0

2017-02-19 05:24 UTC, elicoidal commented on geoengine_partner/models/partner.py
> +    geo_point = fields.GeoPoint('Addresse coordinate')
Address or Addressee?

2017-02-20 10:54 UTC, yvaucher commented on geoengine_partner/models/partner.py
> +    geo_point = fields.GeoPoint('Addresse coordinate')
Oops was Addresses and wanted to remove plural the frenchy way...

2017-02-20 11:01 UTC, yvaucher commented
@elicoidal Updated

2017-04-28 10:06 UTC, merged