[10.0][MIG] geoengine_partner
OCA/geospatial pull request #135
Opened 2017-04-05 14:49 UTC by petrus-v

2017-04-10 13:46 UTC, yvaucher commented
Please base this on https://github.com/OCA/geospatial/pull/128

2017-04-28 10:06 UTC, yvaucher requested changes
Please rebase this on the changes made in 9.0 with PR #128

2017-04-28 10:06 UTC, yvaucher commented on geoengine_partner/README.rst
> +<https://github.com/OCA/{project_repo}/issues>`_. In case of trouble, please
s/project_repo/geospatial

2017-04-28 10:06 UTC, yvaucher commented on geoengine_partner/__manifest__.py
>   'active': False,
travis raised this issue:
geoengine_partner/__manifest__.py:5: [C8103(manifest-deprecated-key), ] Deprecated key "active" in manifest file

2017-04-28 12:30 UTC, dreispt commented on geoengine_partner/views/geo_partner_view.xml
> +        <field name="symbol_binary">iVBORw0KGgoAAAANSUhEUgAAACAAAAAfCAYAAACGVs+MAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJ
FYI is is possible to provide binary content as a relative path to the actual file in the repo.

2017-04-28 12:32 UTC, dreispt commented
TraviCI build is failing.

2023-03-20 12:52 UTC, closed without merging