[11.0][ADD] Support of Swisstopo layers
OCA/geospatial pull request #188
Opened 2019-03-19 10:02 UTC by asaunier

Similar to the changes suggested in 12.0, see https://github.com/OCA/geospatial/pull/187

The layers creation method has been moved from ``GeoengineMixin`` to a distinct class that is explicitely instanciated by the widget or renderer, because it seems not possible to override a mixin using Odoo's ``include()``.

2019-04-01 13:47 UTC, yvaucher commented
See fixes done in #187

2019-04-01 13:47 UTC, yvaucher requested changes
TODO: backport fixes from #187

2019-04-12 16:02 UTC, asaunier commented
@yvaucher Updated. This PR is in sync with #187

2019-04-16 13:06 UTC, yvaucher approved these changes

2019-04-16 13:12 UTC, merged