[12.0] Fix default_extent in views
OCA/geospatial pull request #257
Opened 2020-05-19 14:04 UTC by TDu

Convert the extent information from string to number when opening an
empty view.
Although the default_extent is set with a default value on creation, the
field can be set to null so make sure a default value is used.

This is to attend https://github.com/OCA/geospatial/issues/252

2020-06-04 08:42 UTC, sebalix approved these changes

2020-06-05 07:21 UTC, i-vyshnevska approved these changes

2020-06-08 12:10 UTC, yvaucher requested changes
Thanks.

Here is a couple of improvement suggestions.

2020-06-08 12:10 UTC, yvaucher commented on base_geoengine/static/src/js/widgets/geoengine_widgets.js
>                  var extent = this.defaultExtent.split(', ');
could we take the opportunity to be more resilient on this split?
```suggestion
                var extent = this.defaultExtent.replace(/\s/g, '').split(',');
```

2020-06-08 12:10 UTC, yvaucher commented on base_geoengine/static/src/js/widgets/geoengine_widgets.js
> +                });
Using `map` might be simpler here.

```suggestion
                extent = extent.map(coord => Number(coord));
```

2020-06-09 13:48 UTC, TDu commented
@yvaucher Thanks for the suggestion, works well

2020-06-10 09:15 UTC, yvaucher approved these changes

2020-06-10 09:16 UTC, merged