[14.0][MIG] Migrated a base_google_map module.
OCA/geospatial pull request #290
Opened 2021-04-07 07:52 UTC by AmmarOfficewalaSerpentCS

2021-04-07 07:52 UTC, AmmarOfficewalaSerpentCS commented
@smangukiya , 
Please review this PR.

2021-04-08 05:18 UTC, AmmarOfficewalaSerpentCS commented
@murtuzasaleh , @dreispt, @max3903 , @brian10048  
can you please review this PR?

2021-05-18 20:30 UTC, patrickrwilson approved these changes
A few very small changes requested but no blockers.

2021-05-18 20:30 UTC, patrickrwilson commented on base_google_map/data/google_maps_libraries.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
This line is no longer needed (since v11)

2021-05-18 20:30 UTC, patrickrwilson commented on base_google_map/views/res_config_settings.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
This line is no longer needed (since v11)

2021-05-18 20:30 UTC, patrickrwilson commented on base_google_map/views/res_config_settings.xml
> +    <data>
data tag no longer needed.

2021-05-18 20:30 UTC, patrickrwilson commented on base_google_map/data/google_maps_libraries.xml
> +    <data noupdate="1">
data tag no longer needed, noupdate should be moved into odoo tag.

2021-06-25 08:59 UTC, AmmarOfficewalaSerpentCS commented
@patrickrwilson Can Please Review it.

2021-06-25 15:50 UTC, smangukiya approved these changes

2021-06-25 16:52 UTC, smangukiya commented
/ocabot merge

2021-06-25 16:53 UTC, smangukiya commented
/ocabot merge nobump

2021-06-25 16:56 UTC, smangukiya commented
@lmignon @yvaucher Would you mind reviewing it and if it looks good then merge it? Appreciated. Thank you

2021-07-03 18:43 UTC, dreispt commented
/ocabot merge nobump

2021-07-05 04:45 UTC, lmignon commented
@dreispt PLZ don't use `nobump` when merging. When you use the `nombup` option, only a 'dev' release is published on pypi..

2021-07-05 04:47 UTC, lmignon requested changes
@AmmarOfficewalaSerpentCS @smangukiya Than you for the migration. Can you check and fix the pre-commit error? https://github.com/OCA/geospatial/pull/290/checks?check_run_id=2980089610#step:4:165

2021-07-07 13:42 UTC, AmmarOfficewalaSerpentCS commented
@lmignon , 
Pre-commit fix 
Can you please review it again ?

2021-07-19 12:42 UTC, Freni-OSI commented
CC: @patrickrwilson

2021-07-19 14:05 UTC, dreispt commented
@lmignon Regarding `nobump`, this is not clear to me.
I'm not comfortable forcing a version bump in the cases it is not needed.
I could not find good guidance on this from the docs I found, and even from the bot source code.
@sbidoul Can you confirm this?

PS: This is off-topic, maybe we should move this discussion elsewhere.

2021-07-20 06:07 UTC, lmignon commented
@dreispt AFAIK without version change, the addon will be published on pypi as a dev version. As result, the installation will only be possible through pip by using the `--dev` flag. The result of the migration should be a stable version not a dev version. That's why a version bump is required.

2021-07-20 07:35 UTC, sbidoul commented
@lmignon @dreispt 

A few things about nobump and round version numbers on PyPI

- When using `ocabot merge patch/minor/major`, the bot bumps version and makes the wheel on the same commit it bumped the version, which leads to a "round" (non-dev) version number. When using nobump or a manual merge, the wheel gets generated on the HEAD of main branch which is not necessarily a commit that bumped the manifest version, which leads to a `.dev` version number (counting the commits since the last manifest bump).
- For migration PRs, I tend to use `patch` to be sure to get a round version number.
- That said, I recently noticed that when there are *only* dev versions, pip picks one even without using `--pre` so it does not actually matter that much in practice.
- It's been a while now that I concluded that these `.dev` versions are not useful for OCA and I reckon that in OCA merging is releasing, and trying to be any smarter than that is never going to work. So for 15.0 I plan to use the new setuptools-odoo versioning mode that adds a 6th digit to the version instead of a `.devN`. So there will no need to worry about all that anymore.

2021-08-12 15:13 UTC, max3903 commented
/ocabot merge patch

2021-08-12 16:16 UTC, merged